export const CITY_LOCATIONS: Record<string, { districts: string[]; neighborhoods: string[] }> = {
  Barcelona: {
    districts: [
      'Eixample',
      'Gràcia',
      'Sarrià-Sant Gervasi',
      'Sants-Montjuïc',
      'Nou Barris',
      'Sant Martí',
      'Horta-Guinardó',
      'Les Corts',
      'Ciutat Vella',
      'Sant Andreu',
    ],
    neighborhoods: [
      'La Sagrada Família',
      'Vila de Gràcia',
      "El Camp de l'Arpa",
      'La Barceloneta',
      'El Raval',
      'El Gòtic',
      'El Born',
      'Poble Sec',
      'Sarrià',
      'Sant Gervasi',
      'Poblenou',
      'El Clot',
      'La Vila Olímpica',
      'Diagonal Mar',
      'Pedralbes',
    ],
  },
  Madrid: {
    districts: [
      'Salamanca',
      'Chamberí',
      'Centro',
      'Retiro',
      'Arganzuela',
      'Carabanchel',
      'Moncloa-Aravaca',
      'Tetuán',
      'Hortaleza',
      'Latina',
    ],
    neighborhoods: [
      'Recoletos',
      'Goya',
      'Lista',
      'Almagro',
      'Trafalgar',
      'Sol',
      'Malasaña',
      'Chueca',
      'Lavapiés',
      'La Latina',
      'Prosperidad',
      'Ciudad Jardín',
      'Aluche',
      'Carabanchel Alto',
    ],
  },
};

export const DISTRICT_NEIGHBORHOODS: Record<string, string[]> = {
  // Barcelona
  Eixample: ['La Sagrada Família'],
  Gràcia: ['Vila de Gràcia'],
  'Sarrià-Sant Gervasi': ['Sarrià', 'Sant Gervasi'],
  'Sants-Montjuïc': ['Poble Sec'],
  'Sant Martí': ['Poblenou', 'El Clot', 'La Vila Olímpica', 'Diagonal Mar', "El Camp de l'Arpa"],
  'Les Corts': ['Pedralbes'],
  'Ciutat Vella': ['La Barceloneta', 'El Raval', 'El Gòtic', 'El Born'],
  'Nou Barris': [],
  'Horta-Guinardó': [],
  'Sant Andreu': [],
  // Madrid
  Salamanca: ['Recoletos', 'Goya', 'Lista'],
  Chamberí: ['Almagro', 'Trafalgar'],
  Centro: ['Sol', 'Malasaña', 'Chueca', 'Lavapiés'],
  Retiro: [],
  Arganzuela: [],
  Carabanchel: ['Aluche', 'Carabanchel Alto'],
  'Moncloa-Aravaca': [],
  Tetuán: [],
  Hortaleza: ['Ciudad Jardín', 'Prosperidad'],
  Latina: ['La Latina'],
};

export const CITIES = Object.keys(CITY_LOCATIONS);
