export const CITY_LOCATIONS: Record<string, { districts: string[]; neighborhoods: string[] }> = {
  Barcelona: {
    districts: [
      'Eixample',
      'Gràcia',
      'Sarrià-Sant Gervasi',
      'Sants-Montjuïc',
      'Nou Barris',
      'Sant Martí',
      'Horta-Guinardó',
      'Les Corts',
      'Ciutat Vella',
      'Sant Andreu',
    ],
    neighborhoods: [
      'La Sagrada Família',
      'Vila de Gràcia',
      "El Camp de l'Arpa",
      'La Barceloneta',
      'El Raval',
      'El Gòtic',
      'El Born',
      'Poble Sec',
      'Sarrià',
      'Sant Gervasi',
      'Poblenou',
      'El Clot',
      'La Vila Olímpica',
      'Diagonal Mar',
      'Pedralbes',
    ],
  },
  Madrid: {
    districts: [
      'Salamanca',
      'Chamberí',
      'Centro',
      'Retiro',
      'Arganzuela',
      'Carabanchel',
      'Moncloa-Aravaca',
      'Tetuán',
      'Hortaleza',
      'Latina',
    ],
    neighborhoods: [
      'Recoletos',
      'Goya',
      'Lista',
      'Almagro',
      'Trafalgar',
      'Sol',
      'Malasaña',
      'Chueca',
      'Lavapiés',
      'La Latina',
      'Prosperidad',
      'Ciudad Jardín',
      'Aluche',
      'Carabanchel Alto',
    ],
  },
};

export const CITIES = Object.keys(CITY_LOCATIONS);
